baseURL = 'https://consumingthoughts.ca/'
languageCode = 'en-us'
title = "Flogical Thoughts"
copyright = 'Florent Muyango' # Used in the footer copyright mention.
enableRobotsTXT = true # IMPORTANT: set to true if you want to use the theme's genAI/LLM web crawler blocking feature.
theme = "poison"

[module]
  [[module.imports]]
    ignoreConfig = false   #no change when enabled...as below too
    ignoreImports = false
    path = "github.com/flogical/hugo-theme"

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about'  # stay on page with '#'
    weight = 10
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'Graph'
    pageRef = '/graph'
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
[params]
  # Set how dates should appear across the site.
  # For format options, visit https://gohugo.io/functions/time/format/
  # Default: :date_long
  dateFormat = ':date_long'

  # Show content graph for single notes and posts.
  # Default: true
  showGraph = true

  description = 'Heeeeey' 

  brand_image = '/images/FloC2.png'  #niiice!!

  email_url = "mailto://muyango3@gmail.com"
  ##facebook_url = "https://facebook.com"
  github_url = "https://github.com/fmcyamwe"
  instagram_url = "https://www.instagram.com/iamflogic/"
  linkedin_url = "https://www.linkedin.com/in/florent-muyango/"
  tryhackme_url = "https://tryhackme.com"
  # signal_url = "https://signal.org"
  # bluesky_url = "https://bsky.app"

  # Author details for the JSON-LD structured data.
  [params.author]
    name = 'Florent Muyango'
    email = 'muyango3@gmail.com'

  # About page setup--rework to not use menu...
  [params.about]
    recentProjectsLimit = 3
    recents = ['Blu', 'GPlanner', 'Iam'] ##list of projects but filter content for recent pages instead
  
  # also About page setup for sidebar menus ##naming..sheesh
  [params.recent]
    [[params.recent.about]]
      name = 'About Me'
      url = '/about'   # pageRef
      pre = '<i class="fa-solid fa-code"></i>'
      weight = 10
    [[params.recent.about]]
      name = 'Recent Projects'
      pre = '<i class="fa-solid fa-code"></i>'
      url = '/recent'  # pageRef
      weight = 20


  # Homepage setup
  [params.home]
    # Display recent blog posts on the homepage.
    # Default: true
    showRecentPosts = true

    # Set how many recent blog posts to show.
    # Default: 3
    recentPostsLimit = 3

    # Display recent notes on the homepage.
    # Default: true
    showRecentNotes = true

    # Set how many recent notes to show.
    # Default: 5
    recentNotesLimit = 5

  # Notes page setup
  [params.notes]
    # Set the number of notes to list on each page.
    # Default: 20
    pageSize = 20

    # Show a filter option for note categories above the notes list.
    # Default: true
    showCategoryFilter = true

  # Footer setup
  [params.footer]
    # Specify the Creative Commons license to apply to your content.
    # Options: `by`, `by_sa`, `by_nc`, `by_nc_sa`, `by_nd`, `by_nc_nd`, `zero`, `none`
    # Learn more at https://creativecommons.org/share-your-work/cclicenses/
    # Default: none
    creativeCommonsLicense = 'by_sa'

    # Show Creative Commons icons for the selected license.
    # Default: true
    showCreativeCommonsIcons = true

    # Show a credit link to the Today I Learned theme in the footer.
    # Default: true
    showThemeCredit = true

  # robots.txt setup
  # IMPORTANT: remember to set `enableRobotsTXT = true` in your site's hugo.toml file.
  [params.robotstxt]
    # Block CommonCrawl from indexing your site. CommonCrawl data is often used to train AI models.
    # Learn more at https://commoncrawl.org/ccbot
    # Default: false
    blockCC = true

    # Block various crawlers associated with AI and machine learning model training.
    # Crawler list from https://github.com/ai-robots-txt/ai.robots.txt
    # Default: false
    blockAI = true